apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa 
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  namespace:
    monitoring-site

spec: 
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: backend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80