resources:
- ../../base
- backend-hpa.yaml


patches:
- path: backend-patch.yaml
  target:
    kind: Rollout
    name: backend
- path: frontend-patch.yaml
  target:
    kind: Rollout
    name: frontend

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ludoowg/monitoring-site-backend
  newName: ludoowg/monitoring-site-backend
  newTag: 2232ffd2e576f7d7901f2de866a0557d9264e686
- name: ludoowg/monitoring-site-frontend
  newName: ludoowg/monitoring-site-frontend
  newTag: 2232ffd2e576f7d7901f2de866a0557d9264e686
