resources:
- ../../base
- backend-hpa.yaml


patches:
- path: backend-patch.yaml
  target:
    kind: Rollout
    name: backend
- path: frontend-patch.yaml
  target:
    kind: Rollout
    name: frontend

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ludoowg/monitoring-site-backend
  newName: ludoowg/monitoring-site-backend
  newTag: 3abb62dd7584634ec382f3e20b6c36ea6cb98ec6
- name: ludoowg/monitoring-site-frontend
  newName: ludoowg/monitoring-site-frontend
  newTag: 3abb62dd7584634ec382f3e20b6c36ea6cb98ec6
