resources:
- ../../base
- backend-hpa.yaml


patches:
- path: backend-patch.yaml
  target:
    kind: Rollout
    name: backend
- path: frontend-patch.yaml
  target:
    kind: Rollout
    name: frontend

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ludoowg/monitoring-site-backend
  newName: ludoowg/monitoring-site-backend
  newTag: 7c8ad98e5305a8dadcf4c21584adb75bc4f74d10
- name: ludoowg/monitoring-site-frontend
  newName: ludoowg/monitoring-site-frontend
  newTag: 7c8ad98e5305a8dadcf4c21584adb75bc4f74d10
