resources:
  - backend-depl.yaml
  - backend-service.yaml
  - frontend-depl.yaml
  - frontend-service.yaml
  - gateway.yaml
  - httproute.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - monsealedsecret.yaml
  
namespace:
  monitoring-site
